{% set name = "qt-collapsible-section-pyside6" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qt-collapsible-section-pyside6-{{ version }}.tar.gz
  sha256: 56c777d32225f215ab620599bdc3512eb49203e09baadf21221b41a57ae36d4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - pyside6

test:
  imports:
    - qt_collapsible_section

about:
  home: https://github.com/eyalk11/qt-collapsible-section
  summary: This is a simple collapsable section for PySide6
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dokempf
